Feature : Biometric KYC
smileidentity/flutter pull request #42
Opened 2024-01-08 13:22 UTC by jumaallan

Story: N/A

## Summary

Added Biometric KYC on Flutter

## Known Issues

Any shortcomings in your work. This may include corner cases not correctly handled or issues related
to but not within the scope of your PR. Design compromises should be discussed here if they were not
already discussed above.

## Test Instructions

Concise test instructions on how to verify that your feature works as intended. This should include
changes to the development environment (if applicable) and all commands needed to run your work.

## Screenshot

If applicable (e.g. UI changes), add screenshots to help explain your work.

2024-01-08 16:50 UTC, jumaallan commented on example/lib/main.dart
> +                                "https://webhook.site/a3d19f24-769a-46f2-997c-d186c3ae70ea",
Let me remove it. Its a generated url I use to test callbacks

2024-01-10 10:15 UTC, vanshg requested changes

2024-01-10 10:15 UTC, vanshg commented on example/lib/main.dart
> +        biometricKYCButton(context)
Let's match the style used above with `enhancedKyc`
```suggestion
        biometricKycButton(context)
```

2024-01-10 10:15 UTC, vanshg commented on ios/Classes/SmileIDBiometricKYC.swift
> +                country:  args["userId"] as? String ?? "",
This should be `args["country"]`

2024-01-10 10:15 UTC, vanshg commented on ios/Classes/SmileIDBiometricKYC.swift
> +            userId: args["userId"] as? String ?? "user-\(UUID().uuidString)",
Let's use the helper methods that are available in the iOS SDK
```suggestion
            userId: args["userId"] as? String ?? generateUserId(),
```

2024-01-10 10:15 UTC, vanshg commented on ios/Classes/SmileIDBiometricKYC.swift
> +            jobId: args["jobId"] as? String ?? "job-\(UUID().uuidString)",
same here, `generateJobId()`

2024-01-10 10:15 UTC, vanshg commented on lib/smile_id_biometric_kyc.dart
> +        "idType": idType,
We're missing `country` here

2024-01-10 10:17 UTC, vanshg commented on example/lib/main.dart
> +                                "https://webhook.site/a3d19f24-769a-46f2-997c-d186c3ae70ea",
It was left in intentionally in the sample app as a way to verify that the callback is delivered

2024-01-10 10:45 UTC, jumaallan commented on example/lib/main.dart
> +        biometricKYCButton(context)
Done

2024-01-10 10:47 UTC, jumaallan commented on ios/Classes/SmileIDBiometricKYC.swift
> +            userId: args["userId"] as? String ?? "user-\(UUID().uuidString)",
Done

2024-01-10 10:47 UTC, jumaallan commented on ios/Classes/SmileIDBiometricKYC.swift
> +            jobId: args["jobId"] as? String ?? "job-\(UUID().uuidString)",
Done

2024-01-10 10:50 UTC, jumaallan commented on lib/smile_id_biometric_kyc.dart
> +        "idType": idType,
Good catch - fixed

2024-01-10 12:58 UTC, jumaallan commented on example/lib/main.dart
> +                                "https://webhook.site/a3d19f24-769a-46f2-997c-d186c3ae70ea",
Someone can see data posted on it - so we can remove it from the code and add it when testing only

2024-01-10 12:59 UTC, merged