Make iOS networking methods async
smileidentity/flutter pull request #80
Opened 2024-06-15 00:57 UTC by vanshg

Story: https://app.shortcut.com/smileid/story/12926

## Summary

Updates networking methods to use asynchronous Swift code

## Known Issues

This can go in once https://github.com/smileidentity/ios/pull/183 is released

## Test Instructions

Run jobs from the Flutter sample app

2024-06-18 16:35 UTC, tobitech requested changes

2024-06-18 21:59 UTC, vanshg commented on ios/Classes/SmileIDPlugin.swift
> +                    )!,
These are in do-catch blocks, and we need valid files in order to complete this request. If they are invalid, we will run the catch block

2024-06-19 05:20 UTC, tobitech approved these changes

2024-06-19 06:34 UTC, tobitech commented on ios/Classes/SmileIDPlugin.swift
> +                completion(.success(try await SmileID.api.getJobStatus(request: request.toRequest()).toResponse()))
Probably trivial but I think explicitly specifying the type of `response` would allow the compiler to infer the type while maintaining readability.
Something like:
`let response: FlutterSmartSelfieJobStatusResponse = try await SmileID.api.getJobStatus(request: request.toRequest())`
`completion(.success(response.toResponse()))`

2024-06-19 14:18 UTC, vanshg commented on ios/Classes/SmileIDPlugin.swift
> +                completion(.success(try await SmileID.api.getJobStatus(request: request.toRequest()).toResponse()))
Good call

2024-06-19 14:26 UTC, tobitech approved these changes
Looks good!

2024-06-19 14:33 UTC, merged